### ISSUE TITLE
CFE WebService

### ISSUE THREAD

**Issue by cesartolosa** [CFEMexico/reto071#1]
Cuándo se nos proporcionará acceso al WebService de CFE para incorporarlo a nuestros prototipos?

**Comment by vladimir-rojas** [comment]
Buen día, hay alguna noticia acerca de este tema?

**Comment by ememorato** [comment]
Sí Estimados, el web service se les va a proporcionar el Viernes, según lo que me platica Carlos Vega de CFE.

**Comment by cesartolosa** [comment]
Buenas noches... Alguna novedad en cuanto al webservice?

**Comment by ememorato** [comment]
Hola @cesartolosa – recibí un correo de Carlos Vega ahorita diciendo que probablemente hoy se les hará llegar el webservice. :dancer: :dancers:

**Comment by cesartolosa** [comment]
Buenas noches @ememorato ... alguna novedad? no hemos recibido ningún correo con información del webservice :(

**Comment by Durandante** [comment]
Hola, aún ninguna novedad con lo del Web Service?
También tengo otra duda,  ¿nos podrán también proporcionar una base de datos de los lugares donde se puede pagar?

**Comment by ememorato** [comment]
Hola a todos,

Ya recibí una parte del web service, la cosa es que antes de podérselos enviar, tienen que firmar una carta de confidencialidad de CFE (es ahuevo esto).

Estoy correteando la carta para que ya les llegue y para ya mandarles el web service parcial y la otra parte la mandamos el miércoles o jueves.

Lo bueno es que recorrimos la fecha una semana, entonces eso reduce la presión. Pero yo meto presión a Carlos. :)

**Comment by cesartolosa** [comment]
Gracias @ememorato esperamos el documento para firmarlo.

**Comment by cesartolosa** [comment]
Otra pregunta @ememorato 

Hay algunos puntos que poner en la carta que no nos quedan claros: 
1) Número de Convocatoria, qué número ponemos? el nombre del Reto 071?
2) Debajo del Atentamente va mi nombre? 
3) Donde dice Firma va mi firma o la de alguien mas? 
4) Donde dice Nombre y Firma del apoderado legal va mi nombre y mi firma?

Espero puedas resolver pronto estas dudas para poder enviarte la carta llenada correctamente.

**Comment by Durandante** [comment]
Yo tambíen tengo otra duda @ememorato, en el caso de los que trabajaremos con iOS, es posible tener los UDID de los telefonos de las personas que las quieren probar?

**Comment by pixeleate** [comment]
Hola @ememorato, soy un integrante de Maya Creatives, tengo una pequeña duda con el web service, fíjate que he probado el End Point que nos haz proporcionado y no consigo que me devuelva los métodos, como si no hubiera una definición de los mismos, yo se que ya tenemos los métodos en el PDF que nos enviaste, pero al invocarlos tampoco logro acceder a ellos, si me dirijo directamente al End Point solo recibo el siguiente End Point http://cfecomsai/WebServices/CFEMovil/CFEMovil.svc?wsdl, que no me lleva ningún lugar ya que no tiene métodos definidos. Todo el proceso lo estoy realizando con PHP, pero he verificado el funcionamiento del End Point con otras aplicaciones y no logro hacerlo funcionar, una cosa más en el documento PDF indican que es necesario pasar los parámetros que nos indicas en los diferentes métodos, pero no se menciona, si es necesario pasar los datos de acceso en los headers o si se pasan únicamente como parámetros normales.

Espero me haya dado a entender y me puedas ayudar con mi duda.

De antemano muchas gracias.

**Comment by jesusruizlopez** [comment]
Nosotros también tenemos el mismo problema, no hemos podido consumir los servicios. Nos sería de ayuda un ejemplo o más documentación al respecto.

Saludos.

**Comment by cesartolosa** [comment]
Como dijo mi compañero @jesusruizlopez (somos Pretzel) y @pixeleate de Maya Creatives, pareciera que los el webservice no tuviera métodos disponibles, al crear el cliente del ws basados en el wsdl que obtenemos del siguiente link http://aplicaciones.cfe.gob.mx/WebServices/CFEMovil/CFEMovil.svc?wsdl 
(nótese que no es https como nos dijeron, porque el https nos arroja otra respuesta) obtenemos un Objeto así: 
{
    CFEMovil: {
        BasicHttpBinding_CFEMovil: { }
    }
}
cuando con otros ws el objeto vacío tendría como atributos los métodos disponibles.

Esperamos su respuesta para poder consumir el servicio.

**Comment by ememorato** [comment]
Hola, ya pasé esta duda directamente con gente técnica en CFE y deberían estar respondiendo a sus dudas por este medio en el transcurso de este día. Si no es así, avísenme y meto presión. :trollface:

**Comment by 071CFE** [comment]
Respondiendo a las preguntas que aparecen en el sitio GitHub podemos decir lo siguiente: 

Usuario @pixeleate. Consumir el webservice con protocolo https no está respondiendo correctamente. Por el momento el webservice podrá consumirse con el protocolo http, en la misma dirección: 
http://aplicaciones.cfe.gob.mx/WebServices/CFEMovil/CFEMovil.svc 

Usuario @cesartolosa. El webservice tiene expuestos los métodos para consumo, en el wsdl se observan los métodos que contiene el servicio y en el archivo de especificación enviado se menciona los métodos disponibles para consumo con parámetros de envío u respuesta.

**Comment by jesusruizlopez** [comment]
Hola, hasta el momento no hemos podido consumir los servicios, nos hemos topado con mensajes de error y otro tipo de mensaje sin poder hacer que funcione.

Para efectos de la demostración y presentar el flujo de nuestra aplicación (módulos, pantallas, funcionalidades, características, propuestas de valor, etc), ¿podemos simular estos servicios? o ¿se deben implementar estrictamente en el demo?

Saludos!

**Comment by pixeleate** [comment]
Buenos días yo he podido consumir todos los web service a excepción, del siguiente SELRepoteFalla, siempre me regresa un error indicando Hash invalido, le paso los parámetros que nos enviaron en el PDF y no funciona, la codificación del Hash se realiza correctamente, ya que de lo contrario no funcionarían los otros, podrían verificar si hay algún problema con ese método o si funciona con los parámetros que nos proporcionaron. 

Saludos y muchas gracias.

**Comment by jesusruizlopez** [comment]
Hola, nos sale lo siguiente al querer consumir un servicio.

![captura de pantalla 2014-11-01 a las 16 17 30](https://cloud.githubusercontent.com/assets/2857912/4873628/4e53fad0-621d-11e4-8240-e36209bd05f8.png)

Esto es lo que enviamos

![captura de pantalla 2014-11-02 a las 1 59 24](https://cloud.githubusercontent.com/assets/2857912/4874761/981efbfa-626e-11e4-8e7e-39f5368b71f1.png)

El Hash lo generamos con el algoritmo en C# que se proporciona  y con las instrucciones proporcionadas.

**Comment by 071CFE** [comment]
Usuario @jesusruizlopez. Para poder identificar el problema que ocurre con exactitud, es necesario que proporcione el mensaje de error recibido y que otros tipos de mensaje recibe.
Para la segunda pregunta, se corrigió la cadena enviada para generación del Hash en ese método en particular  (SELReporteFalla), en estos momentos debe responder correctamente y  es posible volver a realizar pruebas.

Usuario @pixeleate. Se corrigió la cadena enviada para generación del Hash en ese método en particular (SELReporteFalla), en estos momentos debe responder correctamente y  es posible volver a realizar pruebas.

**Comment by lalo4ka** [comment]
Existe todavía acceso a la API?? 
me aparece unvailable...
http://aplicaciones.cfe.gob.mx/WebServices/CFEMovil/CFEMovil.svc?wsdl

**Comment by ZERO20** [comment]
Que necesito para tener acceso a la api? alguien puede asesorarme? saludos.

**Comment by sinapsisit** [comment]
Buenas tardes, estuve buscando en internet al respecto pero no he enido suerte.
Lo único que he encontrado fue este sitio... 
Alguien tiene alguna informacion al respecto de la API de CFE?

**Comment by erickgtzh** [comment]
> Buenas tardes, estuve buscando en internet al respecto pero no he enido suerte.
> Lo único que he encontrado fue este sitio...
> Alguien tiene alguna informacion al respecto de la API de CFE?

Conseguiste algo @sinapsisit ?

**Comment by pixeleate** [comment]
No creo que la API sea abierta, esta API requeria credenciales y fue especificamente creada para una convocatoria de la CFE, la verdad la API estaba en version beta, si buscan algo estable no creo que sea por aqui, saludos

**Comment by EteslaSystems** [comment]
Buen dia, alguien sabe algo al respecto de un punto de conexión para el servicio Web o API de la CFE o alguna otra alternativa, para poder efectuar consultas al respecto del historial de consumo de energía de clientes específicos.

**Comment by sinapsis-it** [comment]
> No creo que la API sea abierta, esta API requeria credenciales y fue especificamente creada para una convocatoria de la CFE, la verdad la API estaba en version beta, si buscan algo estable no creo que sea por aqui, saludos

Buen dia Ulises, tendras alguna novedad respecto a esta API? o quien seria el encargado de proporcionarla?

**Comment by zomars** [comment]
En pleno 2021 y aun no tenemos alguna manera de acceder al historial de consumo de nuestro clientes.

**Comment by menarcarlos** [comment]
Igual busco la API oficial de la CFE. Pónganse pilas CFEs,

**Comment by zomars** [comment]
Encontré [esta colección en un perfil publico de postman](https://www.postman.com/vqo9jyW4XtEU5cK1/workspace/admin-store-s-public-workspace/documentation/11104502-3863f39c-c69d-42b9-b16e-bbb770068cd3) pero no he logrado hacerlo funcionar, si alguno tiene suerte por favor comparta el método.

**Comment by Angel-Alvarez6655** [comment]
Pues logré hacer que retornara: `{"status":"0","message":"3"}` usando el endpoint: `https://cfecontigo.cfe.mx:8765/usuarios/nuevologin`
La verdad no sé lo que quiera decir pero lo dejo como aporte

**Comment by zomars** [comment]
Al parecer ya tumbaron el servicio. Volvemos a estar en ceros.

**Comment by Robatortas** [comment]
Nadie ha conseguido informacion nueva sobre esto?

**Comment by Angel-Alvarez6655** [comment]
> Nadie ha conseguido informacion nueva sobre esto?

Negativo. De un momento de Julio 2022 el endpoint dejó de funcionar, al parecer migraron el host así que toca rebuscar para encontrar el nuevo endpoint y el puerto

**Comment by juangom** [comment]
Alguien tiene idea de como siquiera registrarse con la CFE como consumidor de la API?

**Comment by zomars** [comment]
Para quien siga llegando aquí buscando una API para obtener datos de recibos de CFE: monté un servicio self-serve que lo resuelve. Sin NDAs, sin esperar a que CFE libere nada.

Le pasas RPU (12 dígitos) + nombre del titular y te regresa el recibo parseado en JSON: consumo histórico hasta 24 meses, lecturas, demanda, factor de potencia, esquema de generación distribuida (NETMET para usuarios con paneles solares), conceptos de facturación, fechas de corte/límite, etc. Funciona para tarifas residenciales (1, 1A–1F, DAC) y comerciales (GDMTO, etc.).

El tiempo que me hubiera ahorrado haber tenido este servicio hace años: parser robusto del CFDI, manejo de bimestrales vs mensuales, normalización de encoding (acentos), fechas en ISO 8601, mapeo de FacturaAnt al historial, reintentos automáticos cuando CFE tira la sesión, caché por usuario hasta el siguiente corte, y la infraestructura de billing.

Originalmente lo armé para un cotizador solar y lo abrí público. https://cfe-api.fly.dev/ — documentación, ejemplos en Python/Node/Go/cURL y `llms.txt` en [zomars/cfe-api-docs](https://github.com/zomars/cfe-api-docs).

**EDIT:** Por obvias razones el código del servicio no es público. Pero si suficiente gente se suscribe, consideraré hacerlo open source más adelante.
