### ISSUE TITLE
Fecha de presentación de prototipos

### ISSUE THREAD

**Issue by cesartolosa** [CFEMexico/reto071#2]
Los integrantes de Pretzel radicamos en Culiacán Sinaloa y para poder asistir a la presentación de prototipos debemos comprar los boletos de avión con anticipación para que nos salgan más baratos y podamos cubrir el costo. 

Nos confirman por favor la fecha en la que se presentarán los prototipos para hacer los arreglos necesarios?

**Comment by netoxico** [comment]
En la pagina http://retos.datos.gob.mx/organizaciones/8/retos/6-reto071 esta como fecha de entrega de prototipo el día 27 de octubre, es esta la nueva fecha? o se cambiara? por favor confirmar la fecha.

Saludos

**Comment by Durandante** [comment]
Pues se suponía que iban a ver si dado que tardaron 2 días en dar los resultados también extendían la fecha de entrega 2 días, si alguien sabe algo al respecto, les agradecería que lo comunicarán.

**Comment by ememorato** [comment]
La nueva fecha de entrega será el Lunes 3 de Noviembre. Y con respecto al webservice, estoy metiendo presión a Carlos para que ya lo haga llegar.

**Comment by wgdomenzain** [comment]
Gracias Eme!

**Comment by ememorato** [comment]
¡Por nada :D!

**Comment by cesartolosa** [comment]
Buenas tardes.

Una pregunta @ememorato, la fecha para enviar el prototipo se recorrió al Lunes 3 de Noviembre, nos gustaría saber entonces cuál es la fecha, lugar y hora de la demostración presencial para poder comprar los boletos con suficiente antelación y podamos cubrir el costo de traslado de Culiacán al lugar en el que se lleve a cabo la demostración. 

Agradeceremos nos proporciones esta información a fin de hacer los arreglos correspondientes y estar presentes en dicho evento.

**Comment by netoxico** [comment]
## Confusión:

Me llego este correo
![retos_presentaciones](https://cloud.githubusercontent.com/assets/540956/4780197/2b073d8c-5c5d-11e4-8a0f-c9cc744958bf.png)

Según entiendo entonces la entrega de prototipo sera el dia 3 de noviembre y la presentación de prototipos el día 12 de noviembre?
Pueden aclarar este punto por favor.

Saludos.

**Comment by jesusruizlopez** [comment]
Yo también tengo esa duda, se sube el prototipo el día 3 y el 12 se presenta en vivo? Me imagino que en ese lapso todavía se puede mejorar el prototipo?

**Comment by tlacoyodefrijol** [comment]
Hola @netoxico @jesusruizlopez el día 3 se manda el prototipo para que durante esos diez días los funcionarios de la dependencia lo pueda usar. Después del 3 no se podrá hacer cambios al código.

**Comment by vladimir-rojas** [comment]
Hola! tengo una duda, en un correo nos llegó una imagen con la fecha de la presentación el día 12 de noviembre de 10 a 12:30 hrs. Pero después recibimos una actualización de la invitación de Mariana Courtney de 11 a 13:30 hrs. ¿tomamos esta última actualización como la fecha de la presentación?

**Comment by tlacoyodefrijol** [comment]
Hola @vladimir-rojas, efectivamente hubo un cambio de horario a las 11 AM.Esa es la fecha y hora exacta de la presentación.
