### ISSUE TITLE
Base de Datos Lugares de Pago

### ISSUE THREAD

**Issue by vladimir-rojas** [CFEMexico/reto071#4]
Hola! ¿nos pueden decir por favor que valor representa cada columna del excel que contiene los datos de los Centros de Atención a Clientes (estado, latitud, longitud)? Algunos se deducen pero otros no tanto.

**Comment by ememorato** [comment]
Hola Vladimir, pregunté esto a Carlos hace unos días, pero no ha contestado. :(

**Comment by vladimir-rojas** [comment]
Hola M, nos respondieron por correo electrónico esta duda mandando un nuevo archivo de excel con las cabeceras de lo que representa cada columna. Gracias! :)

**Comment by ememorato** [comment]
Perfecto @vladimir-rojas :dancer: :dancers:
